import { useState, useEffect } from "react";
import Head from "next/head";
import Collages from "../components/Collages";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>jake_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.main}>
          <Collages styles={styles}/>
        </div>
      </main>
    </div>
  );
}
