import React from "react";
import Head from "next/head";
import Toolbar from "@mui/material/Toolbar";
import Work from "components/Work";
import styles from "styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>jake_portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/public/fonts/TWKLausanne-300.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/public/fonts/TWKLausanne-400.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <main>
        <Toolbar />
          <div>
            <Work styles={styles} />
          </div>
      </main>
    </div>
  );
}
