name: Jake Website Tests

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'run name'
        # Default value if no value is explicitly provided
        default: 'smoke'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 2.7.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Build
        run: |
          gem install bundler
          gem update --system
          BUNDLE_GEMFILE="./Gemfile" bundle install

      - name: Run tests
        run: |
          bundle exec rspec spec/features/smoke_tests/jakeportfolio/jake_portfolio_spec.rb

      - name: confirm name
        run: echo "tests ${{ github.event.inputs.name }} complete"