name: Jake Website Tests

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Build
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rspec spec/features/smoke_tests/jakeportfolio/jake_portfolio_spec.rb